### PR TITLE
1st attempt at a commit

### PR DESCRIPTION
**Pull request by Cody-Daffinson**
Let me know if there's anything else I can do to fix this

### CODE REVIEW

**Comment by barrycumbie** [comment]
@Cody-Daffinson FINALLY A PR FROM YOU!

Looks good on first scan but I do need a link (here in the comments) to your ```active test site``` and the ```Nu``` to that ```active test site```. See card #20 for an example of the links I want.

**Comment by Cody-Daffinson** [comment]
On line 16 I thought that I had linked my github and on line 30 I thought I had done the link to Nu checker correctly. Are these both wrong?

**Comment by Cody-Daffinson** [comment]
I fixed my link I think

**Comment by Cody-Daffinson** [comment]
Im not sure what the issue with this is but I should be able to fix it once I know what it is.

**Comment by barrycumbie** [comment]
Hi @Cody-Daffinson 

Good news is, it looks like your code is good & you've done Dev 02 as well...so you can submit this SAME PR for Dev 02. 

Before I ```squash & merge``` I still want what I asked for earlier

>Looks good on first scan but I do need a link (here in the comments) to your active test site and the Nu to that active test site. See card #20 for an example of the links I want.

So....see card #20 and most of the other accepted/closed PRs. On those you will see in the comments, the DEV giving me a nice and neat LINK RIGHT HERE IN THE COMMENTS so I can click and review a test version of their code. Also, they have a Nu link for that same test page. So nice and neat for me.

**Comment by Cody-Daffinson** [comment]
My active test sight
https://Cody-Daffinson.github.io/dev-challenge-01/docs/dev-profile/codys-dev-profile.html

my Nu checker
https://validator.w3.org/nu/?doc=https%3A%2F%2Fbarrycumbie.github.io%2Fdev-challenge-01%2Fdev-profile%2Fcodys-dev-profile.html

**Comment by barrycumbie** [comment]
killin me here...this link goes nowhere. 

https://Cody-Daffinson.github.io/dev-challenge-01/docs/dev-profile/codys-dev-profile.html

**Comment by Cody-Daffinson** [comment]
neither does the link in card #20.
our links are identical minus our personal usernames. I clicked on her link and it took me to the same 404 page as mine but I thought thats what you wanted because that's what you approved.

**Comment by Cody-Daffinson** [comment]
maybe this?
https://barrycumbie.github.io/dev-challenge-01/dev-profile/codys-dev-profile.html

**Comment by Cody-Daffinson** [comment]
I'm completely baffled at this point, I might just need to set up another meeting with you

**Comment by barrycumbie** [comment]
ya, we obviously not connecting on this. I'll take it from the top. 

- THE REPO: https://github.com/barrycumbie/dev-challenge-01 
- THE PRODUCT: https://barrycumbie.github.io/dev-challenge-01/
- YOUR PROFILE: https://barrycumbie.github.io/dev-challenge-01/dev-profile/codys-dev-profile.html
> remember this is just that blank initial file I merged in to get your started. No content is on this until I merge the code from your FORK

- YOUR FORK: https://github.com/cody-daffinson/dev-challenge-01/
- YOUR TEST ENV: https://cody-daffinson.github.io/dev-challenge-01 👈🏼 ```404 ERROR```
>hint: maybe you haven't set up your github pages **FORK > Settings > Pages**
- YOUR ACTIVE TEST SITE: https://cody-daffinson.github.io/dev-challenge-01/docs/dev-profile/codys-dev-profile.html

**Comment by Cody-Daffinson** [comment]
I didn't have my github pages set up for some reason but that cleared up a lot of confusion for me. 

I'm sorry. 

My active test site
https://cody-daffinson.github.io/dev-challenge-01/docs/dev-profile/codys-dev-profile.html

**Comment by Cody-Daffinson** [comment]
issues with Nu checker should be fixed. probably not though with my history

**Comment by Cody-Daffinson** [comment]
There was an error for a space in the base 64 image that i copied and pasted but I think i fixed it.

**Comment by barrycumbie** [comment]
image

**Pull request merged**
