### PR TITLE
I have completed DEV-1

### PR DESCRIPTION
**Pull request by jhumphrey3**

### CODE REVIEW

**Comment by jhumphrey3** [comment]
+ NU validator: https://validator.w3.org/nu/?doc=https%3A%2F%2Fjhumphrey3.github.io%2Fdev-challenge-01%2Fdocs%2Fdev-profile%2Fhumphreys-dev-profile.html
+ Dev Profile: https://jhumphrey3.github.io/dev-challenge-01/docs/dev-profile/humphreys-dev-profile.html

**Comment by barrycumbie** [comment]
okay okay, not bad @jhumphrey3  👏🏼👏🏼👏🏼👏🏼👏🏼 

do one fix for me...one more commit and I can squash & merge this on line 69:

your code: 
``` <a href="https://validator.w3.org/nu/?doc=https%3A%2F%2Fjhumphrey3.github.io%2Fdev-challenge-01%2Fdocs%2Fdev-profile%2Fhumphreys-dev-profile.html" target="_blank">Page's validity</a>```

but think about the FUTURE...when I merge this....what will your page's URL be then? Can you predict that & put that in the link? 
> HINT: Your link on your page won't work at first, but then will work after I merge it into the repo

``` <a href="https://validator.w3.org/nu/?doc=https%3A%2F%2F``` + ```something different here``` + ```dev-challenge-01%2Fdocs%2Fdev-profile%2Fhumphreys-dev-profile.html" target="_blank">Page's validity</a>```

**Comment by jhumphrey3** [comment]
I have fixed the nu link and update html file with my dev profile links.

**Comment by barrycumbie** [comment]
really not a fan of doubling up TWO challenges in one. There are some issues for your Dev 02 that I now have to work out once I merge this 😠 needed a fresh git pull on that index first .

**Pull request merged**
