### PR TITLE
Create dev-03-gitcommands

### PR DESCRIPTION
**Pull request by olivia7n**
Create page detailing git commands

### CODE REVIEW

**Comment by barrycumbie** [comment]
Not bad @olivia7n but need to make those cmds clearer. From your code, I'd type in:

```git add: add file contents to the index```

but that would error out. Wouldn't I need 

```shell
# to add a file named "name-of-changed-file.php" that has changed & in your current directory location  
git status
# this will display in RED FONT any files that have changed that are not yet added to git's staging area

```shell
git add name-of-changed-file.php
# tip, run a git status again: the changed file should now be listed in GREEN FONT
```

* could you elaborate a bit more on your html file? 
* did you run this through Nu? That would be nice to let lil ol @barrycumbie know. 
* look over there 👉🏼 link this PR to your issue # & assing yourself too 🙏🏼

**Comment by olivia7n** [comment]
Assigned myself and created iss request

**Comment by olivia7n** [comment]
I'm confused on how to get a live Nu link

**Comment by barrycumbie** [comment]
Ya don't need a ```live``` Nu link in this case...You could just copy/paste your ```<html>``` directly into Nu and leave me a note like this:

**TEST**
* ```Nu Validity Checker``` ✅  source code copy/paste with no errors on Nu.
*

**Comment by barrycumbie** [comment]
I realized that you did not drop this file in the course-content/ directory but directly into the docs/

Since I already closed this and deleted your branch, 

Create a new issue to move your file to the proper place, 

Work on a new branch and name it this way: 

```iss``` + ```the Issue number autogenerated by github```

for example, maybe it is 

```git branch iss122```

then a new PR. A quick fix 😉

**Pull request merged**
