### PR TITLE
dev01 first pull--hopefully complete

### PR DESCRIPTION
**Pull request by bendavis91**

### CODE REVIEW

**Comment by barrycumbie** [comment]
@bendavis91 whoa...super almost complete. Just 2 things...not even rejecting your PR, you should just be able to update with a new commit or two. 

1) in the comments here, give me the links to your ```active test site``` and a pointer to Nu of that same site. Example in #20. 

2) also, for the actual Nu in your "soon to be merged" ```html``` file, you have to PREDICT in the FUTURE what the file path will be to that on Nu. Look at Harris' Nu link: https://barrycumbie.github.io/dev-challenge-01/dev-profile/harris-dev-profile.html

**Comment by bendavis91** [comment]
active test site: https://bendavis91.github.io/dev-challenge-01/docs/dev-profile/davis-dev-profile

nu validator pointer: https://validator.w3.org/nu/?doc=https%3A%2F%2Fbendavis91.github.io%2Fdev-challenge-01%2Fdocs%2Fdev-profile%2Fdavis-dev-profile

I fixed my nu checker in my html on local, so should I just make a new pull request?

**Comment by barrycumbie** [comment]
so close...same comment from before:

also, for the actual Nu in your "soon to be merged" html file, you have to PREDICT in the FUTURE what the file path will be to that on Nu. Look at Harris' Nu link: https://barrycumbie.github.io/dev-challenge-01/dev-profile/harris-dev-profile.html

**Comment by barrycumbie** [comment]
sure but not sure if the ```docs``` is in my pathway. If it don't work you can fix it in Dev 02.

**Comment by barrycumbie** [comment]
@bendavis91 oh...make sure to submit this link again to CNVS or else no credit given.

**Pull request merged**
