### PR TITLE
Fixed nu checker link

### PR DESCRIPTION
**Pull request by AndrewEstacio**

### CODE REVIEW

**Comment by AndrewEstacio** [comment]
nu checker for active test link: https://validator.w3.org/nu/?doc=https%3A%2F%2FAndrewEstacio.github.io%2FAEstacio-dev-profile.html

**Comment by barrycumbie** [comment]
@AndrewEstacio coulda included this too: https://AndrewEstacio.github.io/AEstacio-dev-profile.html but I grabbed it from your Nu link.

**Comment by barrycumbie** [comment]
plz do not delete files like index.html.

**Comment by barrycumbie** [comment]
yay!

**Pull request merged**
