### PR TITLE
issue92

### PR DESCRIPTION
**Pull request by jpowelliv**
content & web page on scrum. I put everything in a folder hope that doesn't mess up anything.

### CODE REVIEW

**Comment by barrycumbie** [comment]
I think this is super cool...except from the challenge:

>  * drop needed files in lib/

you can see that a previous dev already created the ```/lib``` dir, so you can move your stuff there. 

```shell
# moving some files and stuff from CLI (or just use your GUI) 
# from your docs folder
mv course-content/dev3/img/framework.png lib/img/framework.png
# repeat for the rest of your images and styles too (mv to lib/styles)
# once your dev3/ is empty, make sure to kill it
rm -r dev3/
# the end.
```

you will have to do some ```git``` cmds after ```git add``` and maybe ```git rm``` and all.

**Comment by barrycumbie** [comment]
oh and @jpowelliv don't forget to link this pull to your issue 👉🏼 ```linked issues```

**Comment by jpowelliv** [comment]
This Pull Request fixes issue #92. @barrycumbie

**Comment by barrycumbie** [comment]
way cleaner DIR/

**Pull request merged**
