### PR TITLE
updating pull

### PR DESCRIPTION
**Pull request by OliveHamm14**

### CODE REVIEW

**Comment by barrycumbie** [comment]
need a link to your active test site & the Nu of the ATS, example #20

**Comment by barrycumbie** [comment]
For me to asses: 

https://olivehamm14.github.io/dev-challenge-02/dev-profile/hammond-dev-profile.html

:point_up that is your ```active test site```

**Comment by barrycumbie** [comment]
alright @OliveHamm14, we need 3 things, i think

1. add in the link to this PR/comment: Nu to your ```active test site```
1. on your fork, one more commit to change your Nu link from ```your profile name``` to ```my profile name```
1. submit on CNVS this URL

**Comment by OliveHamm14** [comment]
> alright @OliveHamm14, we need 3 things, i think
> 
> 1. add in the link to this PR/comment: Nu to your `active test site`
> 2. on your fork, one more commit to change your Nu link from `your profile name` to `my profile name`
> 3. submit on CNVS this URL



1. Link to Nu checker:
2. Old Nu: https://validator.w3.org/nu/?doc=https%3A%2F%2Fthekaysev.github.io%2Fdev-challenge-01%2Fdocs%2Fdev-profile%2Fsevigne-dev-profile.html
3. New Nu: https://validator.w3.org/nu/?doc=https%3A%2F%2Fbarrycumbie.github.io%2Fdev-challenge-02%2Fdev-profile%2Fhammond-dev-profile.html
4. Changed fork
5. Submitted to canvas

**Comment by barrycumbie** [comment]
alright @OliveHamm14, we need 3 things, i think

1. add in the link to this PR/comment: Nu to your active test site
1. on your fork, one more commit to change your Nu link from your profile name to my profile name
1. <strike>submit on CNVS this URL</strike>

**Comment by barrycumbie** [comment]
@OliveHamm14 

for my requested item no. 1, add a comment for the Nu, you gave me these two things: https://olivehamm14.github.io/dev-challenge-02/dev-profile/hammond-dev-profile.html


- Old Nu: https://validator.w3.org/nu/?doc=https%3A%2F%2Fthekaysev.github.io%2Fdev-challenge-01%2Fdocs%2Fdev-profile%2Fsevigne-dev-profile.html

- New Nu: https://validator.w3.org/nu/?doc=https%3A%2F%2Fbarrycumbie.github.io%2Fdev-challenge-02%2Fdev-profile%2Fhammond-dev-profile.html

I need the Nu to your ```active test site```:

**Comment by barrycumbie** [comment]
alright @OliveHamm14, we need 3 things, i think

1. add in the link to this PR/comment: Nu to your active test site
1. <strike> on your fork, one more commit to change your Nu link from your profile name to my profile name </strike> 
1. <strike> submit on CNVS this URL</strike>

**Comment by OliveHamm14** [comment]
> alright @OliveHamm14, we need 3 things, i think
> 
> 1. add in the link to this PR/comment: Nu to your active test site


Nu Checker for Active link:
https://validator.w3.org/nu/?doc=https%3A%2F%2Folivehamm14.github.io%2Fdev-challenge-02%2Fdev-profile%2Fhammond-dev-profile.html

**Comment by barrycumbie** [comment]
closing this PR but doing a workaround on my end to add your file in. 

```shell
# on git, update main
# create branch 
git branch iss107
git remote add other https://github.com/OliveHamm14/dev-challenge-02.git
git fetch other
git pull other
git add docs/dont-do-this.html
git commit -m 'whatever' # wont let me stash
git pull other main

From https://github.com/OliveHamm14/dev-challenge-02
 * branch            main       -> FETCH_HEAD
Auto-merging docs/index.html
CONFLICT (content): Merge conflict in docs/index.html
Auto-merging docs/dev-profile/davis-dev-profile.html
CONFLICT (add/add): Merge conflict in docs/dev-profile/davis-dev-profile.html
CONFLICT (modify/delete): docs/dev-instructions/dev-02-instructions.md deleted in 0089cd5374836c41ef683b293b60400a1a5b912c and modified in HEAD. Version HEAD of docs/dev-instructions/dev-02-instructions.md left in tree.
CONFLICT (modify/delete): docs/dev-instructions/dev-01-instructions.md deleted in 0089cd5374836c41ef683b293b60400a1a5b912c and modified in HEAD. Version HEAD of docs/dev-instructions/dev-01-instructions.md left in tree.
Automatic merge failed; fix conflicts and then commit the result.
KEL2-0249-MGFWL:dev-challenge-01 bcumbie$ nano docs/index.html 
KEL2-0249-MGFWL:dev-challenge-01 bcumbie$ nano docs/dev-profile/davis-dev-profile.html 
KEL2-0249-MGFWL:dev-challenge-01 bcumbie$ git merge
error: Merging is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.
KEL2-0249-MGFWL:dev-challenge-01 bcumbie$ git status
On branch iss107
You have unmerged paths.
  (fix conflicts and run "git commit")
  (use "git merge --abort" to abort the merge)

Changes to be committed:

	new file:   docs/dev-profile/hammond-dev-profile.html

Unmerged paths:
  (use "git add/rm <file>..." as appropriate to mark resolution)

	deleted by them: docs/dev-instructions/dev-01-instructions.md
	deleted by them: docs/dev-instructions/dev-02-instructions.md
	both added:      docs/dev-profile/davis-dev-profile.html
	both modified:   docs/index.html

KEL2-0249-MGFWL:dev-challenge-01 bcumbie$ git add docs/dev-profile/hammond-dev-profile.html 
KEL2-0249-MGFWL:dev-challenge-01 bcumbie$ git add docs/dev-profile/davis-dev-profile.html 
KEL2-0249-MGFWL:dev-challenge-01 bcumbie$ git add docs/index.html 
KEL2-0249-MGFWL:dev-challenge-01 bcumbie$ git status
On branch iss107
You have unmerged paths.
  (fix conflicts and run "git commit")
  (use "git merge --abort" to abort the merge)

Changes to be committed:

	modified:   docs/dev-profile/davis-dev-profile.html
	new file:   docs/dev-profile/hammond-dev-profile.html
	modified:   docs/index.html

Unmerged paths:
  (use "git add/rm <file>..." as appropriate to mark resolution)

	deleted by them: docs/dev-instructions/dev-01-instructions.md
	deleted by them: docs/dev-instructions/dev-02-instructions.md

KEL2-0249-MGFWL:dev-challenge-01 bcumbie$ git rm docs/dev-instructions/dev-01-instructions.md 
docs/dev-instructions/dev-01-instructions.md: needs merge
rm 'docs/dev-instructions/dev-01-instructions.md'
KEL2-0249-MGFWL:dev-challenge-01 bcumbie$ git rm docs/dev-instructions/dev-02-instructions.md 
docs/dev-instructions/dev-02-instructions.md: needs merge
rm 'docs/dev-instructions/dev-02-instructions.md'
KEL2-0249-MGFWL:dev-challenge-01 bcumbie$ git status
On branch iss107
All conflicts fixed but you are still merging.
  (use "git commit" to conclude merge)

Changes to be committed:

	deleted:    docs/dev-instructions/dev-01-instructions.md
	deleted:    docs/dev-instructions/dev-02-instructions.md
	modified:   docs/dev-profile/davis-dev-profile.html
	new file:   docs/dev-profile/hammond-dev-profile.html
	modified:   docs/index.html

KEL2-0249-MGFWL:dev-challenge-01 bcumbie$ git merge
fatal: You have not concluded your merge (MERGE_HEAD exists).
Please, commit your changes before you merge.
KEL2-0249-MGFWL:dev-challenge-01 bcumbie$ git commit -m 'mergin'
[iss107 fa72ed8] mergin
KEL2-0249-MGFWL:dev-challenge-01 bcumbie$ git merge
fatal: No remote for the current branch.
KEL2-0249-MGFWL:dev-challenge-01 bcumbie$ git status
On branch iss107
nothing to commit, working tree clean
KEL2-0249-MGFWL:dev-challenge-01 bcumbie$ ls
LICENSE		README.md	docs		index.html
KEL2-0249-MGFWL:dev-challenge-01 bcumbie$ git branch
  base64pic
  hotfix/exampleUpdate
  hotfix/index
  hotfix/restoreDev1and2
* iss107
  iss46
  iss92
  josephalsup-main
  main
KEL2-0249-MGFWL:dev-challenge-01 bcumbie$ ls
LICENSE		README.md	docs		index.html
KEL2-0249-MGFWL:dev-challenge-01 bcumbie$ cd docs/
KEL2-0249-MGFWL:docs bcumbie$ ls
course-content		dev-profile		joshua-dev-profile.html
dev-03-gitcommands	dont-do-this.html	lib
dev-instructions	index.html		noah-dev-profile
KEL2-0249-MGFWL:docs bcumbie$ cd dev-profile/
KEL2-0249-MGFWL:dev-profile bcumbie$ ls
Estacio-dev-profile.html	joe_dev.html
alsup-dev-profile.html		josh-dev-challenge.html
codys-dev-profile.html		luan-dev-profile.html
davis-dev-profile.html		owen-dev-profile.html
escobar-dev-profile.html	reid-dev-profile.html
hammond-dev-profile.html	sevigne-dev-profile.html
humphreys-dev-profile.html	sherrill.html
KEL2-0249-MGFWL:dev-profile bcumbie$ 
git pull  
```

**Comment by OliveHamm14** [comment]
Thank you for all your help, Dr. Cumbie. Is there anything else I need to do on my end for this?

**Pull request closed without merging**
