### PR TITLE
Reid's Dev 1 Pull Request

### PR DESCRIPTION
**Pull request by reidhoman**
My updated Dev 1 pull request.

### CODE REVIEW

**Comment by barrycumbie** [comment]
Code looks good @reidhoman :clap :clap :clap. 

your Nu link on your file needs to point to the FUTURE: (that is, imagine what the URL will be for your PRODUCTION PAGE once I merge it into the REPO). 

Secondly, on your comments, gimme the link to your active test site and the Nu to that site, like in #20

**Comment by reidhoman** [comment]
Thanks for your feedback!

*I updated my Future Nu link in my file

Active link: https://reidhoman.github.io/dev-challenge-01/docs/dev-profile/reid-dev-profile.html

Active Nu Validator Link: https://validator.w3.org/nu/?doc=https%3A%2F%2Freidhoman.github.io%2Fdev-challenge-01%2Fdocs%2Fdev-profile%2Freid-dev-profile.html

**Comment by barrycumbie** [comment]
one tiny thing...from your Nu link:

> Active Nu Validator Link: https://validator.w3.org/nu/?doc=https%3A%2F%2Freidhoman.github.io%2Fdev-challenge-01%2Fdocs%2Fdev-profile%2Freid-dev-profile.html

you are getting one warning ⚠️ . Can you clean this up? @reidhoman

**Comment by reidhoman** [comment]
Fixed the warning. Thanks for the feedback!

**Pull request merged**
