### PR TITLE
File Starting

### PR DESCRIPTION
**Pull request by JGantDill**

### CODE REVIEW

**Comment by barrycumbie** [comment]
Okay @JGantDill Looks like you are moving along. 

Now, reply back in the comments section here the two other things I need:

First: a link to your ```active test site``` so something like: ...JGantDill.github.io/whatever-your-repo-is-named/then-the-folder-pathway-to-your-file/your-dev-file.html

Also: include the link to the results of the Nu checker to that ```active test site``` (run it in Nu, then copy the URL).

**Comment by JGantDill** [comment]
I have done what I am suppose to do for Dev Challenge 02.

**Comment by barrycumbie** [comment]
Fix line 61: 

```diff
- Nu Checker Validator Link: <a href="https://validator.w3.org/nu/?doc=https%3A%2F%2Fjgantdill.github.io%2Fdev-challenge-01%2Fdocs%2Fdev-profile%2Fgant-dev-profile.html" target="_blank">here</a>
+ Nu Checker Validator Link: <a href="https://validator.w3.org/nu/?doc=https%3A%2F%2Fbarrycumbie.github.io%2Fdev-challenge-01%2Fdev-profile%2Fgant-dev-profile.html" target="_blank">here</a>
```

**Comment by barrycumbie** [comment]
> I have done what I am suppose to do for Dev Challenge 02.

*supposed

And...what kind of comment is this? Is it a request? This is the issue card for DC1, what does that have to do with DC2?

**Comment by barrycumbie** [comment]
image

**Pull request merged**
