### PR TITLE
kaylin pull request

### PR DESCRIPTION
**Pull request by thekaysev**

### CODE REVIEW

**Comment by barrycumbie** [comment]
@thekaysev not denying this PR but would like:

- link to your active test page
- link to Nu for your active test page.

**Comment by thekaysev** [comment]
@barrycumbie 
here's the active link: https://thekaysev.github.io/dev-challenge-01/docs/dev-profile/sevigne-dev-profile.html

**Comment by thekaysev** [comment]
@barrycumbie 
here's the link to my Nu Validator with my active link: https://validator.w3.org/nu/?doc=https%3A%2F%2Fthekaysev.github.io%2Fdev-challenge-01%2Fdocs%2Fdev-profile%2Fsevigne-dev-profile.html

**Comment by thekaysev** [comment]
@barrycumbie the Nu validator link still works for my new commit

**Review by barrycumbie — CHANGES_REQUESTED** [review]
two tiny tiny changes:

Line 12
```diff
-  <a href="github.com/thekaysev">GitHub</a>
+  <a href="github.com/thekaysev">[text that denotes it is not going to THE GitHub but to your profile, specifically]</a>
```

And line 60

```diff
- <a href="https://validator.w3.org/nu/?doc=https%3A%2F%2Fthekaysev.github.io%2Fdev-challenge-01%2Fdocs%2Fdev-profile%2Fsevigne-dev-profile.html" target="_blank">Check the Validity of this page!</a>
+ <a href="https://validator.w3.org/nu/?doc=https%3A%2F%2Fbarrycumbie.github.io%2Fdev-challenge-01%2Fdev-profile%2Fsevigne-dev-profile.html" target="_blank">Check the Validity of this page!</a>
```

**Comment by thekaysev** [comment]
@barrycumbie updated the changes you asked for

**Pull request merged**
