### PR TITLE
fixed nu checker to barrycumbie github, added html target to nu checker.

### PR DESCRIPTION
**Pull request by Chelfert**
Dev challenge 01 - Changed nu checker link to open in a new tab.
- changed the nuchecker to check the link on barrycumbie's git

### CODE REVIEW

**Comment by barrycumbie** [comment]
link to ```active test site```
and Nu to that ☝🏼 too

**Comment by Chelfert** [comment]
Here is a link to the NU checker -
https://validator.nu/?doc=https%3A%2F%2Fchelfert.github.io%2Fdev-challenge-01%2Fdev-profile%2Fchelfert.html

The link on my active site links to when it will be in your main branch.

**Comment by Chelfert** [comment]
Here is a link to my active site -

https://chelfert.github.io/dev-challenge-01/dev-profile/chelfert.html

**Comment by barrycumbie** [comment]
@Chelfert didn't we talk about fixing your link targets?

```html
<a href="whatever" target="_blank">
  a link that opens up off your site needs to load in a new tab since there isn't a return link on the destination page!
</a>
```

* fix those 2 links! *

And, the Nu link on your page is this: 

https://validator.nu/?doc=https%3A%2F%2Fchelfert.github.io%2Fdev-challenge-01%2Fdev-profile%2Fchelfert.html

** doesn't ** take me to 
>to when it will be in your main branch.

it would need to be more like: ```...barrycumbie.github.io...```

**Comment by Chelfert** [comment]
It seems that I did not push the right file, I'm still struggling to figure out exactly what I'm doing regarding git. My apologies.

**Pull request closed without merging**
