### PR TITLE
Added Chelfert to dev profile and link to dev profile in index.html

### PR DESCRIPTION
**Pull request by Chelfert**
Submission for Dev Challenge 01

### CODE REVIEW

**Comment by barrycumbie** [comment]
any links for me here? 

Like a nice link in the comments to your fork / GitHub pages of an active test site? 
A link to the Nu checker of the test site? 

See #20 for an example.

**Comment by Chelfert** [comment]
Here is an active link to my page - 

https://chelfert.github.io/dev-challenge-01/dev-profile/chelfert.html

**Comment by Chelfert** [comment]
Here is a link to the Nu Validity checker - 

https://validator.nu/?doc=https%3A%2F%2Fchelfert.github.io%2Fdev-challenge-01%2Fdev-profile%2Fchelfert.html

**Comment by barrycumbie** [comment]
> https://validator.nu/?doc=https%3A%2F%2Fchelfert.github.io%2Fdev-challenge-01%2Fdev-profile%2Fchelfert.html

is ths the same?


https://validator.w3.org/nu/?doc=https%3A%2F%2Fchelfert.github.io%2Fdev-challenge-01%2Fdev-profile%2Fchelfert.html

**Review by Chelfert — COMMENTED** [review]
Added chelfert to dev profile folder and linked dev profile to index.html

**Comment by barrycumbie** [comment]
Welcome to the repo

image

**Pull request merged**
