### PR TITLE
Pull Request #1

### PR DESCRIPTION
**Pull request by michaelowen22**

### CODE REVIEW

**Comment by barrycumbie** [comment]
@michaelowen22 try doing a better PR title, don't need a # in there cuz GH does those for us.

AND AND AND, I want 

1. a link to your ```active test site````
2. a link to your Nu of your ```active test site```

**Comment by michaelowen22** [comment]
here is the active link https://michaelowen22.github.io/dev-challenge-01/docs/dev-profile/owen-dev-profile.html

**Comment by michaelowen22** [comment]
here's the link to my Nu Validator with my active link: https://validator.w3.org/nu/?doc=https%3A%2F%2Fmichaelowen22.github.io%2Fdev-challenge-01%2Fdocs%2Fdev-profile%2Fowen-dev-profile.html

**Comment by barrycumbie** [comment]
I did merge this but there are two issues to fix...do these when you submit Dev 02:

1. Your Nu link on your published/merged page is this: 
```https://validator.w3.org/nu/?doc=https%3A%2F%2Fmichaelowen22.github.io%2Fdev-challenge-01%2Fdev-profile%2Fowen-dev-profile.html```
shouldn't it be
```https://validator.w3.org/nu/?doc=https%3A%2F%2F. [someone else] github.io%2Fdev-challenge-01%2Fdev-profile%2Fowen-dev-profile.html```

2. oh, and you had a tiny error on that Nu checker. The point is for you to clean these all out before submission. Should be all green!

**Pull request merged**
