### PR TITLE
added course-content dir iss72

### PR DESCRIPTION
**Pull request by williamoyen**
Hopefully, this works now.

Added the course-content dir for Dev-03 files

### CODE REVIEW

**Comment by barrycumbie** [comment]
Make no mistake, this is a good & clean ISSUE > CODE > PR but this is not a Dev Challenge 3. 

Maybe you could submit this as a Dev Challenge 04? You notice something that needs to be done on the REPO or PRODUCT and create an issue (sounds 🎯 ). You can create the issue for 5 points.

So, submit this same link but for Dev Challenge 04. 
> spoiler alert: I will reject cuz I want more on an Issue card: some more description/background to the problem (with links and stuff), and assigning difficulty to it, and a user-story and all...but we can cross that bridge later.

**Comment by williamoyen** [comment]
@barrycumbie I still planned on doing my other issue for dev-03, this was just something that needed to be done since dev-03 says the files need to live in course-content/ so I did this just so everyone can put dev-03 in the directory mentioned in the instructions

**Comment by barrycumbie** [comment]
@williamoyen okay, okay. I'll squash & merge BUT was trying to get you to get some points by using Dev Challenge 04. 

One tip I'll do for you, over there 👉🏼 link your PR to your ISSUE. That way a merged PR auto-closes your Issue 😮

**Comment by williamoyen** [comment]
@barrycumbie  Oh okay, I appreciate it, I'll find something else for dev-04 should not be a problem

**Pull request merged**
