### PR TITLE
dev profile

### PR DESCRIPTION
**Pull request by cescobar13124**

### CODE REVIEW

**Comment by barrycumbie** [comment]
@cescobar13124 looks like you are just getting started with a placeholder file. That's fine...it came through okay. Now you just need to keep up the ```commits``` and resubmit on CNVS when you are ready for me to take a look

**Comment by barrycumbie** [comment]
okay @cescobar13124 just give me a couple of links in this PULL comments (see #20 for example) 

- link to your ```active test site```
- and the Nu to that ☝🏼 ```a.t.s.```

**Comment by barrycumbie** [comment]
I bet...on your ACTUAL html page...you will need that Nu link as well: 

Not this: 

```https://validator.w3.org/nu/?doc=https%3A%2F%2Fthekaysev.github.io%2Fdev-challenge-01%2Fdocs%2Fdev-profile%2Fsevigne-dev-profile.html```

imagine 🤔 what this link will become once the MERGE is approved. 

```https://validator.w3.org/nu/?doc=https%3A%2F%2Fbarrycumbie.github.io%2Fdev-challenge-01%2Fdev-profile%2Fsevigne-dev-profile.html```

**Comment by cescobar13124** [comment]
Active test site:
https://cescobar13124.github.io/dev-challenge-01/docs/dev-profile/escobar-dev-profile.html

NU:
https://validator.w3.org/nu/?doc=https%3A%2F%2Fcescobar13124.github.io%2Fdev-challenge-01%2Fdocs%2Fdev-profile%2Fescobar-dev-profile.html

**Comment by barrycumbie** [comment]
code review 

line 25 needs a ```target="_blank"```

```
 <a href="https://github.com/cescobar13124">This is my GitHub</a>
```

**Comment by barrycumbie** [comment]
type in here too

```

    <h4>Dev Eniroment: </h4>
    <ul>
        <li> Windows 10 </li>
        <li> Mac 
        <li>
        <li> Notepad ++ </li>
        <li> Codeanywhere </li>
    </ul>
```

**Comment by cescobar13124** [comment]
Test link: https://cescobar13124.github.io/dev-challenge-01/dev-profile/escobar-dev-profile.html
NU: https://validator.w3.org/nu/?doc=https%3A%2F%2Fcescobar13124.github.io%2Fdev-challenge-01%2Fdev-profile%2Fescobar-dev-profile.html

**Pull request merged**
